// Generated by CoffeeScript 1.7.1
var continuousCollision;

continuousCollision = function() {
  var bodyDef, i, shapeDef, _i;
  bodyDef = new b2BodyDef;
  shapeDef = new b2BoxDef;
  shapeDef.density = 4;
  shapeDef.restitution = 1.4;
  shapeDef.extents.Set(45, 4.5);
  bodyDef.AddShape(shapeDef);
  shapeDef = new b2BoxDef;
  shapeDef.density = 4;
  shapeDef.restitution = 1.4;
  shapeDef.extents.Set(4.5, 81);
  shapeDef.localPosition.Set(-43.5, -70.5);
  shapeDef.localRotation = -.2;
  bodyDef.AddShape(shapeDef);
  shapeDef = new b2BoxDef;
  shapeDef.density = 4;
  shapeDef.restitution = 1.4;
  shapeDef.extents.Set(4.5, 81);
  shapeDef.localPosition.Set(43.5, -70.5);
  shapeDef.localRotation = .2;
  bodyDef.AddShape(shapeDef);
  bodyDef.position.Set(320, 240);
  world.CreateBody(bodyDef);
  for (i = _i = 0; _i <= 4; i = ++_i) {
    addBody({
      name: "ball " + (i + 1),
      x: Math.random() * 300 + 250,
      y: Math.random() * 320 + 20,
      radius: Math.random() * 10 + 5,
      friction: .3,
      density: 1,
      restitution: 1.1
    });
  }
  return 'Continuous Collision Detection';
};
