// Generated by CoffeeScript 1.7.1
var addBody, animate, bodies, ground, initBox2d, initDraw, world;

world = null;

initBox2d = function() {
  var aabb;
  aabb = new b2AABB;
  aabb.minVertex.Set(0, 0);
  aabb.maxVertex.Set(640, 480);
  return window.world = new b2World(aabb, new b2Vec2(0, 300), true);
};

initDraw = function() {
  var canvas, ctx;
  canvas = document.getElementById('canvas');
  ctx = canvas.getContext('2d');
  return window.world.SetDebugDraw({
    ctx: ctx,
    width: 640,
    height: 480
  });
};

addBody = function(params) {
  var body, bodyDef, height, i, p, points, radius, rotation, shapeDef, width, x, y, _i, _len;
  params || (params = {});
  x = params.x || 0;
  y = params.y || 0;
  width = params.width;
  height = params.height;
  radius = params.radius;
  points = params.points;
  rotation = params.rotation;
  bodyDef = new b2BodyDef;
  if (radius) {
    shapeDef = new b2CircleDef;
    shapeDef.radius = radius || 15;
    bodyDef.AddShape(shapeDef);
  } else if (points) {
    shapeDef = new b2PolyDef;
    shapeDef.vertexCount = points.length;
    for (i = _i = 0, _len = points.length; _i < _len; i = ++_i) {
      p = points[i];
      shapeDef.vertices[i].Set(p[0], p[1]);
    }
    bodyDef.AddShape(shapeDef);
  } else {
    shapeDef = new b2BoxDef;
    shapeDef.extents.Set((parseInt(width, 10) || 30) * .5, (parseInt(height, 10) || 30) * .5);
    bodyDef.AddShape(shapeDef);
  }
  if (rotation) {
    shapeDef.localRotation = rotation;
  }
  shapeDef.density = params.density || 0;
  shapeDef.friction = params.friction || 0;
  shapeDef.restitution = params.restitution || 0;
  bodyDef.position.Set(x, y);
  body = world.CreateBody(bodyDef);
  return body.m_userData = {
    name: params.name,
    additional: params.additional || {}
  };
};

ground = function() {
  addBody({
    name: 'floor',
    x: 320,
    y: 475,
    width: 640,
    height: 10,
    friction: .1,
    density: 0
  });
  addBody({
    name: 'left wall',
    x: 5,
    y: 240,
    width: 10,
    height: 480,
    friction: .1,
    density: 0
  });
  return addBody({
    name: 'right wall',
    x: 635,
    y: 240,
    width: 10,
    height: 480,
    friction: .1,
    density: 0
  });
};

bodies = function() {
  addBody({
    name: 'square',
    x: 310,
    y: 30,
    width: 50,
    height: 50,
    friction: .2,
    density: 1
  });
  addBody({
    name: 'circle',
    x: 320,
    y: 100,
    radius: 15,
    friction: 0.2,
    restitution: 0.2,
    density: 1
  });
  return addBody({
    name: 'static triangle',
    x: 320,
    y: 300,
    points: [[0, 0], [100, 100], [-100, 125]],
    friction: .1,
    density: 0
  });
};

animate = function() {
  window.world.Step(1 / 60, 4);
  window.world.DebugDraw();
  return requestAnimationFrame(animate);
};

window.onload = function() {
  initBox2d();
  initDraw();
  ground();
  bodies();
  return animate();
};
