// Generated by CoffeeScript 1.7.1
var addBody, animate, bodies, ctx, ground, initBox2d, initDraw, world;

world = null;

ctx = null;

initBox2d = function() {
  var aabb;
  aabb = new b2AABB;
  aabb.minVertex.Set(0, 0);
  aabb.maxVertex.Set(640, 480);
  return window.world = new b2World(aabb, new b2Vec2(0, 300), true);
};

initDraw = function() {
  var canvas;
  canvas = document.getElementById('canvas');
  return window.ctx = canvas.getContext('2d');
};

addBody = function(params) {
  var body, bodyDef, height, p, points, radius, rotation, shapeDef, width, x, y, _i, _len;
  params || (params = {});
  x = params.x || 0;
  y = params.y || 0;
  width = params.width;
  height = params.height;
  radius = params.radius;
  points = params.points;
  rotation = params.rotation;
  bodyDef = new b2BodyDef;
  if (radius) {
    shapeDef = new b2CircleDef;
    shapeDef.radius = radius || 15;
    bodyDef.AddShape(shapeDef);
  } else if (points) {
    shapeDef = new b2PolyDef;
    shapeDef.vertexCount = points.length;
    for (_i = 0, _len = points.length; _i < _len; _i++) {
      p = points[_i];
      shapeDef.vertices[i].Set(p[0], p[1]);
    }
    bodyDef.AddShape(shapeDef);
  } else {
    shapeDef = new b2BoxDef;
    shapeDef.extents.Set((parseInt(width, 10) || 30) * .5, (parseInt(height, 10) || 30) * .5);
    bodyDef.AddShape(shapeDef);
  }
  if (rotation) {
    shapeDef.localRotation = rotation;
  }
  shapeDef.density = params.density || 0;
  shapeDef.friction = params.friction || 0;
  shapeDef.restitution = params.restitution || 0;
  bodyDef.position.Set(x, y);
  body = world.CreateBody(bodyDef);
  return body.m_userData = {
    name: params.name,
    additional: params.additional || {}
  };
};

ground = function() {
  return console.log('ground');
};

bodies = function() {
  return console.log('bodies');
};

animate = function() {
  window.world.Step(1 / 60, 4);
  window.world.DebugDraw(window.ctx);
  return requestAnimationFrame(animate);
};

window.onload = function() {
  initBox2d();
  initDraw();
  ground();
  bodies();
  return animate();
};
